spring.application.name=e-commerce

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=bKJ6tsMaBWD9FzcXfc2gWJAJbjLCsDmmC3+gHVbFHCo=
jwt.expiration=3600000

RAZORPAY_KEY_ID: your_razorpay_key_id
RAZORPAY_KEY_SECRET: your_razorpay_key_secret
