spring.application.name=e-commerce

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=bKJ6tsMaBWD9FzcXfc2gWJAJbjLCsDmmC3+gHVbFHCo=
jwt.expiration=3600000

razorpay.key.id=rzp_test_SqhjjgXMpuftmJ
razorpay.key.secret=YjSUMeQyuC39AcmImzxZnHTd